### ISSUE TITLE
1. User can submit a form to pair with another user for a selected activity 

### ISSUE THREAD

**Issue by nickkniola** [nickkniola/hang-full-stack#1]
## 💰 Feature

User can submit a form to pair with another user for a selected activity 

1. Looks to see if relevant activity exists in database
2. If not, creates a new activity based on criteria with empty user in accept/reject
3. Both users must accept to be paired

## 🗒️ Notes

Use Google Places API (https://maps.googleapis.com/maps/api/place/textsearch/output?parameters)

## 🖼 Wireframe
<img width="172" alt="Screen Shot 2020-12-22 at 3 50 06 PM" src="https://user-images.githubusercontent.com/65201044/102943598-61ed5580-446d-11eb-8530-a8bcb3bb75d8.png">

## ✅ Tasks

- [x] Setup project
- [x] Create form components
- [x] Save form data to state
- [x] Create search code to handle GET request using fetch to backend server at /api/activities
- [x] Create backend to find and retrieve an activity from the server
- [x] Have data submitted used to search Google Places API with fetch
- [x] Create logic to create new activity based on returned data from Google Places API
- [x] Create logic to match user with other user from database for the activity
- [x] Move communication with Places API and send user input to the server
- [ ] Remove unnecessary dependencies/scripts/code
