### ISSUE TITLE
User can view matches and activities

### ISSUE THREAD

**Issue by nickkniola** [nickkniola/hang-full-stack#14]
## 💰 Feature
User can view matches and activities

## 🗒️ Notes
Data for matches and activities is stored in 'Activities' table in database

## 🖼 Wireframe
<img width="306" alt="Screen Shot 2021-01-04 at 10 35 54 AM" src="https://user-images.githubusercontent.com/65201044/103567606-f5188900-4e78-11eb-8af1-a4e74b1331ba.png">

## ✅ Tasks
- [x] Create a GET express route at '/api/matches/:userId'
- [x] Get all activities from database with a hostId or guestId matching the userId, referencing Users, ActivityTypes tables
- [x] Create an array of all activities
- [x] Create an array of all users matched with
- [x] Send both arrays to client
- [x] Test route with Httpie
- [x] Create frontend Matches and Activities lists for rendering data
- [x] Create fetch GET request for matches/activities on componentDidMount
