### ISSUE TITLE
4.1 User can receive messages with users they pair with

### ISSUE THREAD

**Issue by nickkniola** [nickkniola/hang-full-stack#17]
## 💰 Feature
User can receive messages with users they pair with

## 🗒️ Notes
Use Socket IO: https://socket.io

## 🖼 Wireframe
<img width="190" alt="Screen Shot 2020-12-22 at 4 33 03 PM" src="https://user-images.githubusercontent.com/65201044/102945706-63218100-4473-11eb-98f7-eb99b6bacea0.png">

## ✅ Tasks
- [x] Create server side express route handling GET requests to '/api/messages/:userId/:partnerId'
- [x] Query the SQL database to get matching messages based on userId and partnerId
- [x] Respond to client with data of all messages
- [x] On componentDidMount, have all messages loaded from backend using a fetch GET request to server at '/api/messages/:userId/:partnerId'
- [x] Create front-end logic for displaying messages
- [x] Create server-side socket.io implementation for sending a live message to front-end
- [x] Create front-end socket.io implementation for receiving a live message
- [x] Implement logic to render new message
- [x] Add autoscroll functionality to automatically scroll to latest message
