### ISSUE TITLE
User can register for an account

### ISSUE THREAD

**Issue by nickkniola** [nickkniola/hang-full-stack#19]
## 💰 Feature
User can register for an account

## 🖼 Wireframe
<img width="322" alt="Screen Shot 2021-01-07 at 3 40 53 PM" src="https://user-images.githubusercontent.com/65201044/103957095-cd3a5700-50fe-11eb-97bb-d56683e641ab.png">
<img width="324" alt="Screen Shot 2021-01-07 at 3 41 09 PM" src="https://user-images.githubusercontent.com/65201044/103957097-cdd2ed80-50fe-11eb-9b4e-9a337ca14d1b.png">

## ✅ Tasks
- [x] Create 'Main' component with button linking to Sign Up page
- [x] Create 'SignUp' component with form inputs
- [x] Store form data in state onChange
- [x] Have 'Create Account' button call a method onSubmit
- [x] Create server express route handling POST requests to '/api/auth/sign-up'
- [x] Hash the password for security
- [x] Insert into SQL database the firstName, lastName, email, hashed password
- [x] Respond with userId and token
- [x] Create fetch POST request to '/api/auth/sign-up' in the handleSubmit method
- [x] Store the userId and the token in localStorage
- [x] Forward to 'Pairing' page
- [x] Add authorization middleware module to verify the token
- [x] Add token to every fetch request
