### ISSUE TITLE
2. User can submit a form to pair with another user for a randomly selected activity 

### ISSUE THREAD

**Issue by nickkniola** [nickkniola/hang-full-stack#2]
## 💰 Feature

User can submit a form to pair with another user for a randomly selected activity 

## 🗒️ Notes

Use Google Places API (https://maps.googleapis.com/maps/api/place/textsearch/output?parameters)

1. Looks to see if relevant activity exists in database
2. If not, creates a new activity based on criteria based on interests from settings
3. Both users must accept to be paired

## 🖼 Wireframe
<img width="186" alt="Screen Shot 2020-12-22 at 4 10 57 PM" src="https://user-images.githubusercontent.com/65201044/102944674-551e3100-4470-11eb-8c79-e36bf8d6f213.png">

## ✅ Tasks

- [x] Create Navigation bar to navigate from Pairing page to Random page
- [x] Conditionally change the view by slight alterations to Pairing UI
- [x] Create randomize functionality to randomly pick an activityType for use in both querying database and fetch to Google Places API
- [x] Handle not having a specified preferredActivity in fetch to Google Places API
