### ISSUE TITLE
3. User can accept/reject suggested activity with suggested user

### ISSUE THREAD

**Issue by nickkniola** [nickkniola/hang-full-stack#3]
## 💰 Feature

User can accept/reject suggested activity with suggested user

## 🗒️ Notes

- If activity is accepted, then it is saved in activities table.
- If rejected, finds another location/user of same activity type to pair with.

## 🖼 Wireframe
<img width="169" alt="Screen Shot 2020-12-22 at 4 13 37 PM" src="https://user-images.githubusercontent.com/65201044/102944785-aaf2d900-4470-11eb-9c4f-283804bbf125.png">

## ✅ Tasks

- [x] Create conditional rendering of a Accept/Reject card from state data on submit of Pairing/Random form
- [x] Have 'Reject' button on click invoke handleSubmit method again for new activity
- [x] Have 'Accept' button, depending on whether a 'responseLocation' or 'activityObject' value exists in state, either send a (responseLocation) POST request to /api/activity or (activityObject) PUT request to /api/activities/:activityId
- [x] Create backend SQL to update database for receiving POST to /api/activity or PUT to /api/activities/:activityId
- [x] Have server respond to client side upon successful POST/PUT with relevant data
- [x] Update navigation to use React Router DOM
- [x] Have modal button on click take user to Matches page 
- [x] Refactor SelectActivity component into 4 separate components
- [x] Create Switch routes for 4 components
- [x] Stylize 'No Activity Found' warning
- [x] Re-implement the load screen for when 'Pairing' activity is loading
- [x] Implement the ability to get a random activity from 'Random' screen
- [x] Forward from 'Pairing'/'Random' screens to 'Matches' when an activity is accepted
