### ISSUE TITLE
4. User can send messages to users they pair with

### ISSUE THREAD

**Issue by nickkniola** [nickkniola/hang-full-stack#4]
## 💰 Feature

User can send/receive messages with users they pair with

## 🗒️ Notes
Use Socket IO: https://socket.io

## 🖼 Wireframe
<img width="190" alt="Screen Shot 2020-12-22 at 4 33 03 PM" src="https://user-images.githubusercontent.com/65201044/102945706-63218100-4473-11eb-98f7-eb99b6bacea0.png">

## ✅ Tasks

- [x] Add 'Matches' buttons for navigating to 'Message' page
- [x] Create empty 'Messages' component
- [x] Use React Router to allow for navigation from 'Matches' buttons to 'Message' page and back
- [x] Create user interface for messages, text input, and 'send' button
- [x] Install and use Socket.io in the server for sending messages only to the specified user
- [x] Store sent messages in database
- [x] Implement client side communication to backend including message in body
